### ISSUE TITLE
API Docs

### ISSUE THREAD

**Issue by apizzuto** [IceCubeOpenSource/FastResponseAnalysis#15]
Add API docs to the repository

**Comment by apizzuto** [comment]
I probably won't be here to add API docs, so if someone else decides to fix this, I'd recommend looking into "pandoc," it's what we've used for a few other IceCube projects

**Comment by jessiethw** [comment]
Maybe using Sphinx? (used for csky, seems more straightforward: https://www.sphinx-doc.org/en/master/usage/quickstart.html)
TO DO: figure out how to get added to the IceCube API docs site

**Comment by jessiethw** [comment]
DONE! and added to the repo :)
