### ISSUE TITLE
Small issues from Jessie's first live run

### ISSUE THREAD

**Issue by apizzuto** [IceCubeOpenSource/FastResponseAnalysis#21]
* Weird justify thing with the GFU singlet rate plot
* Skylab version hardcoded
* Slight differences in upper limit plot
* Spatial weights differ by <1% (this is fine)

**Comment by apizzuto** [comment]
Should make the input for alert followup in ISO time instead of MJD time

**Comment by apizzuto** [comment]
Get rid of "new code framework" in the name

**Comment by apizzuto** [comment]
Underscores in skymap path are subscripts

**Comment by apizzuto** [comment]
Need to fix all of the hardcoding in `web_utils` so that Jessie / Abhishek can run this. Might want to brainstorm solutions for how to have multiple people running the code without having to run document.py twice each time.

Change document.py to import from `web_utils` instead of `utils`

**Comment by apizzuto** [comment]
All except the last fixed in the latest round of commits: https://github.com/icecube/FastResponseAnalysis/commit/70d752cfad9fca9dcb2ecdc4058f8c49b371970c

**Comment by apizzuto** [comment]
`web_utils` fix: https://github.com/icecube/FastResponseAnalysis/commit/85f69180698f9e2374e01aad3a56f02898d813f9

**Comment by jessiethw** [comment]
From Aswathi's install:
missing in requirements.txt:
- skylab (maybe tell people to point to their version?)
- IPython

**Comment by apizzuto** [comment]
Cackling that I just got a notification for this, love to see it
