### ISSUE TITLE
Potential Path Issue

### ISSUE THREAD

**Issue by apizzuto** [IceCubeOpenSource/FastResponseAnalysis#22]
@jessiethw might have found a bug with where the listener looks when automating analyses. This is a good first issue for folks new to the code.
https://github.com/icecube/FastResponseAnalysis/blob/6df60e538ab9e4555aa7a518613c6843eaf5d152/fast_response/listeners/gcn_listener.py#L14

**Comment by jessiethw** [comment]
Path issues fixed in #24
