### ISSUE TITLE
Alert ID name

### ISSUE THREAD

**Issue by apizzuto** [IceCubeOpenSource/FastResponseAnalysis#23]
Alert IDs always assume the name of the alert will be IceCube-YYMMDDA but we should change this to include "...B" or "...C" etc.

**Comment by apizzuto** [comment]
Jessie added a flag to manually add this when running in https://github.com/icecube/FastResponseAnalysis/pull/24, but we still need to add something to the listener to figure out when this happens so that it can automatically raise that flag when we are running with listeners

**Comment by jessiethw** [comment]
fixed in https://github.com/icecube/FastResponseAnalysis/pull/25/commits/cc12de9678c912b84e610d6168b3dbec0a83a957
