### ISSUE TITLE
Change to a more deliberate package structure

### ISSUE THREAD

**Issue by apizzuto** [IceCubeOpenSource/FastResponseAnalysis#3]
Reorganize all the files in the directory, make the package pip installable, change from svn style releases to tagged releases in Github

**Comment by adesai90** [comment]
Also maybe move/keep whole code in python 3

**Comment by apizzuto** [comment]
Mainly done, little assurance for backwards compatibility, see https://github.com/IceCubeOpenSource/FastResponseAnalysis/commit/c1ecf9d13ef3caaca2ceb790931c180f889c802e. I need to rewrite scripts that use the `sys.path.append` structure to just a more straightforward `from fast_response import foo` structure. Also need to make scripts directory and move the `run*` scripts there

**Comment by apizzuto** [comment]
Done! See https://github.com/IceCubeOpenSource/FastResponseAnalysis/commit/594c1fbfe615bfee64654d6a780a4c3ba298bd5e
