### ISSUE TITLE
Directory handling in `gw_gcn_listener.py`

### ISSUE THREAD

**Issue by mlincett** [IceCubeOpenSource/FastResponseAnalysis#44]
In `gw_gcn_listener.py` the script expect to find a `PickledMocks` directory in `FAST_RESPONSE_OUTPUT`. This will result in an error if the directory is not created beforehand:
https://github.com/icecube/FastResponseAnalysis/blob/c33a51ba39011cc22b8afaa88c0ac92580cac024/fast_response/listeners/gw_gcn_listener.py#L136-L137

I could not find any other reference to such directory name, so I recommend creating it from the script itself in case it's missing. 

I also suggest using `os.path.join` (or `pathlib.Path`) for concatenating paths (the code currently fails unless `FAST_RESPONSE_OUTPUT` ends with a `/`.

**Comment by mlincett** [comment]
Please also check:
https://github.com/icecube/FastResponseAnalysis/blob/c33a51ba39011cc22b8afaa88c0ac92580cac024/fast_response/listeners/gw_gcn_listener.py#L141

Here `analysis_path` comes from `$FAST_RESPONSE_SCRIPTS` but the scripts looks up for a `../../output` directory which is a bit confusing given that `$FAST_RESPONSE_OUTPUT` is specified separately.

**Comment by jessiethw** [comment]
fixed both in commit 16e9e82 on enhancements/gw branch. It may be best for you to test with that branch, as that is where I'm adding changes, and then can PR with main when all are finished
